### ISSUE TITLE
Standardize Releases

### ISSUE THREAD

**Issue by thisisjoshford** [near/DX#18]
## What

Ensure all repositories for dApp developers have releases accompanied by intelligible release notes.

## Why

To clearly communicate with devs what recent features have been shipped and what issues have been resolved. 
This enables developers to build better software by staying up-to-date with new features they can utilize. 

## Resources

```[tasklist]
### Related Issues
- [ ] https://github.com/near/near-discovery/issues/546
- [ ] https://github.com/near/near-discovery/issues/690
```

**Comment by charleslavon** [comment]
@thisisjoshford we now have release notes auto created on each production release for near-discovery and near-discovery-components. Perhaps that's good enough for now and this can be closed?

**Comment by thisisjoshford** [comment]
We can close this issue but we would like to keep #690 open. I will address my reasoning there.
